runtime: python39

handlers:
- url: /s
  static_dir: static

- url: /scripts
  static_dir: static/js
  
- url: /favicon.ico
  static_files: static/images/favicon_io/favicon-32x32.png
  upload: static/images/favicon_io/favicon-32x32.png

- url: /.*
  script: auto