runtime: python39

handlers:
- url: /s
  static_dir: static_files

- url: /scripts
  static_dir: static_files/js
  
- url: /favicon.ico
  static_files: static_files/images/favicon_io/favicon-32x32.png
  upload: static_files/images/favicon_io/favicon-32x32.png

- url: /.*
  script: auto